@startuml classes

class Article {
    - name: str
    - description: str
    - category: Category
    - brand: Brand
    - minimun_stock: float
    - ean13_code: str

}

class ReceiptType {
    - name: str
    - description: str
    - type: int // 1: in, 0: transfer, -1: out
}

class Receipt {
    - header: ReceiptHeader
    - contents: ReceiptItem
    - footer: ReceiptFooter
}

class ReceiptHeader {
    - submission_date: datetime
    - type: ReceiptType

}

class ReceiptContent {
    - articles: Article
    - quantity: float
    - batch: Batch

}

class ReceiptFooter {
    - total: float

}

class Category {
    - name: str
    - description: str
}

class Brand {
    - name: str
    - description: str
}

class Stock {
    - contents: ReceiptItem
}

class Notification {
    - message: str
    - type: int // 1: info, 0: warning, -1: error
    - date: datetime
}

class Batch {
    - batch_number: int
    - expiration_date: datetime
}

ReceiptHeader --- Receipt
ReceiptItem --- Receipt
ReceiptFooter --- Receipt
Stock --> Article
Category --> Article
Brand --> Article
ReceiptType --> Receipt

@enduml